---
- name: Switch Drift Detection – Cisco 9300
  hosts: 192.168.29.164
  gather_facts: no
  connection: network_cli

  vars:
    ansible_user: admin
    ansible_password: admin@123
    baseline_port_security: true
    baseline_portfast: true
    baseline_storm_control: true

  collections:
    - cisco.ios

  tasks:
    - name: Gather running configuration
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: running_cfg

    - name: Parse interface blocks into list
      set_fact:
        interface_blocks: >-
          {{
            running_cfg.stdout[0]
            | split('\ninterface ')
            | select('match','^GigabitEthernet')
            | list
          }}

    - name: Check compliance on each access-port interface
      loop: "{{ interface_blocks }}"
      loop_control:
        label: "{{ item.split('\n')[0] }}"
      vars:
        iface_block: "{{ item }}"
        iface_name: "{{ item.split('\n')[0] }}"
        portsec_ok: "{{ (baseline_port_security == false) or ('switchport port-security' in iface_block) }}"
        portfast_ok: "{{ (baseline_portfast == false) or ('spanning-tree portfast' in iface_block) }}"
        storm_ok: "{{ (baseline_storm_control == false) or ('storm-control' in iface_block) }}"
      block:
        - name: Report Port-Security status on {{ iface_name }}
          ansible.builtin.debug:
            msg: "Port-Security on {{ iface_name }} : {{ 'COMPLIANT' if portsec_ok else 'NON-COMPLIANT' }}"

        - name: Report PortFast status on {{ iface_name }}
          ansible.builtin.debug:
            msg: "PortFast on {{ iface_name }} : {{ 'COMPLIANT' if portfast_ok else 'NON-COMPLIANT' }}"

        - name: Report Storm Control status on {{ iface_name }}
          ansible.builtin.debug:
            msg: "Storm-Control on {{ iface_name }} : {{ 'COMPLIANT' if storm_ok else 'NON-COMPLIANT' }}"

    - name: Summary for host {{ inventory_hostname }}
      ansible.builtin.debug:
        msg: >
          "Completed interface compliance checks on {{ inventory_hostname }} – inspected {{ interface_blocks | length }} interfaces."
