---
- name: Upgrade Cisco Catalyst 9300 Switch IOS-XE
  hosts: 192.168.29.164
  gather_facts: no
  connection: network_cli

  vars:
    new_image: "cat9k_iosxe.17.15.03.SPA.bin"
    tftp_server: "192.168.29.63"
    image_path: "flash:{{ new_image }}"
    boot_system_cmd: "boot system flash:{{ new_image }}"
    mgmt_vrf: "Mgmt-vrf"
    command_timeout: 2700

  tasks:
    - name: Check connectivity to TFTP server (via Mgmt VRF)
      cisco.ios.ios_command:
        commands:
          - "ping vrf {{ mgmt_vrf }} {{ tftp_server }} repeat 5"
      register: ping_result

    - name: Display ping result
      debug:
        var: ping_result.stdout_lines

    - name: Verify flash space
      cisco.ios.ios_command:
        commands:
          - "show flash: | include bytes"
      register: flash_space

    - name: Display flash space
      debug:
        var: flash_space.stdout_lines

    - name: Copy image from TFTP to switch flash
      cisco.ios.ios_command:
        commands:
          - command: "copy tftp://{{ tftp_server }}/{{ new_image }} flash:"
            prompt:
              - "Address or name of remote host.*\\?"
              - "Source filename \\[{{ new_image }}\\]\\?"
              - "Destination filename \\[{{ new_image }}\\]\\?"
            answer:
              - "{{ tftp_server }}"
              - "{{ new_image }}"
              - "{{ new_image }}"
        check_all: true
        async: "{{ command_timeout }}"
        poll: 0
      register: tftp_copy

    - name: Set boot variable to new image
      cisco.ios.ios_command:
        commands:
          - "configure terminal"
          - "no boot system"
          - "{{ boot_system_cmd }}"
          - "end"
          - "write memory"
      register: boot_out

    - name: Reload the switch to activate new image
      cisco.ios.ios_command:
        commands:
          - command: "reload"
            prompt:
              - 'Proceed with reload\\? \\[confirm\\]'
            answer:
              - "\r"
        async: 300
        poll: 0
      ignore_errors: yes

    - name: Wait for switch to come back
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 60
        timeout: 900
      delegate_to: localhost

    - name: Show version after reload
      cisco.ios.ios_command:
        commands:
          - "show version"
      register: post_version

    - name: Debug version after reload
      debug:
        var: post_version.stdout_lines

    - name: Assert the version is as expected
      assert:
        that:
          - "'17.15.03' in (post_version.stdout_lines[0] | default(''))"
        fail_msg: "Upgrade failed: Version after reload is not 17.15.03"
        success_msg: "Upgrade succeeded to version 17.15.03"
