---
- name: Full Cisco 9300 Upgrade via TFTP (Mgmt-vrf)
  hosts: 192.168.29.164
  gather_facts: no
  connection: network_cli
  collections:
    - cisco.ios

  tasks:
    - name: Save running-config
      cisco.ios.ios_command:
        commands:
          - write memory
        # ensuring enough time for save
        # you can set timeout here if needed
      vars:
        ansible_command_timeout: 120

    - name: Copy running-config to TFTP server
      cisco.ios.ios_command:
        commands:
          - command: "copy system:running-config tftp://192.168.29.23/192.168.29.164_backup"
            prompt:
              - "Address or name of remote host"
              - "Destination filename"
            answer:
              - "192.168.29.23"
              - "192.168.29.164_backup"
      vars:
        ansible_command_timeout: 120

      register: copy_result

    - name: Show result of backup
      debug:
        var: copy_result.stdout_lines
