---
- name: Upgrade Cisco Catalyst 9300 Switch IOS-XE
  hosts: 192.168.29.164
  gather_facts: no
  connection: network_cli

  vars:
    upgrade_image: "cat9k_iosxe.17.15.03.SPA.bin"
    tftp_server: "192.168.29.22"
    remote_image_path: "tftp://{{ tftp_server }}/Users/prabhakaran/Downloads/{{ upgrade_image }}"
    bootflash_image: "bootflash:{{ upgrade_image }}"
    expected_version: "17.15.03"
    # Timeout for long running commands like install
    command_timeout: 2700

  tasks:
    - name: Show current version
      cisco.ios.ios_command:
        commands:
          - "show version"
      register: version_out

    - name: Debug current version
      debug:
        msg: "{{ version_out.stdout[0] }}"

    - name: Copy image via TFTP
      cisco.ios.ios_command:
        commands:
          - "copy {{ remote_image_path }} {{ bootflash_image }}"
        wait_for:
          - "result[0] contains Copy complete"
        retries: 60
        interval: 30
      register: copy_out

    - name: Debug copy result
      debug:
        var: copy_out.stdout_lines

    - name: Verify image MD5 (optional, if you know MD5)
      cisco.ios.ios_command:
        commands:
          - "verify /md5 {{ bootflash_image }}"
      register: md5_out

    - name: Debug MD5 output
      debug:
        var: md5_out.stdout_lines

    - name: Run install add + activate + commit
      cisco.ios.ios_command:
        commands:
          - command: "install add file {{ bootflash_image }} activate commit"
            prompt: 
              - "This operation requires a reload of the system. Do you want to proceed"
            answer:
              - "y"
        wait_for:
          - "result[0] contains install_add_activate_commit: START"
        retries: 5
        interval: 60
      register: install_out

    - name: Debug install output
      debug:
        var: install_out.stdout_lines

    - name: Pause to let installation proceed
      pause:
        minutes: 10

    - name: Trigger reload
      cisco.ios.ios_command:
        commands:
          - command: "reload"
            prompt:
              - "Proceed with reload? [confirm]"
              - "confirm"
            answer:
              - "\n"
        retries: 3
        interval: 10

    - name: Wait for switch to come back
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 60
        timeout: 600
      delegate_to: localhost

    - name: Show version after reload
      cisco.ios.ios_command:
        commands:
          - "show version"
      register: post_version

    - name: Debug version after reload
      debug:
        var: post_version.stdout[0]

    - name: Assert the version is as expected
      assert:
        that:
          - "'{{ expected_version }}' in post_version.stdout[0]"
        fail_msg: "Upgrade failed: Version after reload is not {{ expected_version }}"
        success_msg: "Upgrade succeeded to {{ expected_version }}"
