---
- name: Upgrade Cisco Catalyst 9300 Switch IOS-XE
  hosts: 192.168.29.164
  gather_facts: no
  connection: local

  vars:
    upgrade_image: cat9k_iosxe.17.15.03.SPA.bin
    tftp_server_ip: 192.168.29.22
    remote_image_path: tftp://192.168.29.22/cat9k_iosxe.17.15.03.SPA.bin
    bootflash_image: flash:cat9k_iosxe.17.15.03.SPA.bin
    vrf: Mgmt-vrf
    expected_version: 17.15.03
    copy_timeout: 2700
    install_timeout: 3600
    wait_for_reboot_seconds: 600
    long_command_timeout: 1200

  tasks:
    - name: Show current version
      cisco.ios.ios_command:
        commands:
          - "show version"
      register: version_out

    - name: Debug current version
      debug:
        msg: "{{ version_out.stdout[0] }}"

    - name: Copy image via TFTP
      cisco.ios.ios_command:
        commands:
          - "copy {{ remote_image_path }} {{ bootflash_image }}"
        wait_for:
          - "result[0] contains Copy complete"
        retries: 60
        interval: 30
      vars:
        ansible_command_timeout: "{{ long_command_timeout }}"
      register: copy_out

    - name: Debug copy result
      debug:
        var: copy_out.stdout_lines

    - name: Verify image MD5 (optional)
      cisco.ios.ios_command:
        commands:
          - "verify /md5 {{ bootflash_image }}"
      register: md5_out

    - name: Debug MD5 output
      debug:
        var: md5_out.stdout_lines

    - name: Install and activate new image (install mode)
      cisco.ios.ios_command:
        commands:
          - "install add file {{ bootflash_image }} activate commit"
        prompt:
          - "This operation requires a reload of the system. Do you want to proceed"
        answer:
          - "y"
        wait_for:
          - "result[0] contains install_add_activate_commit"
        retries: 5
        interval: 60
      vars:
        ansible_command_timeout: "{{ long_command_timeout }}"
      register: install_out

    - name: Debug install output
      debug:
        var: install_out.stdout_lines

    - name: Pause to let installation proceed
      pause:
        minutes: 10

    - name: Reload the switch
      cisco.ios.ios_command:
        commands:
          - "reload"
        prompt:
          - "Proceed with reload? [confirm]"
          - "confirm"
        answer:
          - "\n"
      vars:
        ansible_command_timeout: 300

    - name: Wait for switch to come back after reload
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 60
        timeout: 900
      delegate_to: localhost

    - name: Show version after reload
      cisco.ios.ios_command:
        commands:
          - "show version"
      register: post_version

    - name: Debug version after reload
      debug:
        var: post_version.stdout[0]

    - name: Assert correct version
      assert:
        that:
          - "'{{ expected_version }}' in post_version.stdout[0]"
        fail_msg: "Upgrade failed: version after reload is not {{ expected_version }}"
        success_msg: "Upgrade succeeded: version is {{ expected_version }}"
