---
- name: Upgrade Cisco Catalyst 9300 Switch
  hosts: cisco_switches
  gather_facts: no
  connection: network_cli
  vars:
    new_image: "cat9k_iosxe.17.15.03.SPA.bin"
    image_path: "flash:/{{ cat9k_iosxe.17.15.03.SPA.bin}}"
    remote_image_url: "tftp://192.168.29.22/{{ cat9k_iosxe.17.15.03.SPA.bin }}"
    boot_system_cmd: "boot system flash:{{ cat9k_iosxe.17.15.03.SPA.bin }}"
  tasks:
    - name: Copy new image to flash
      ansible.netcommon.net_put:
        src: "{{ remote_image_url }}"
        dest: "{{ image_path }}"

    - name: Verify image checksum
      cisco.ios.ios_command:
        commands:
          - "verify /md5 {{ image_path }}"

    - name: Set boot variable to new image
      cisco.ios.ios_config:
        lines:
          - "{{ boot_system_cmd }}"

    - name: Save running configuration
      cisco.ios.ios_config:
        save_when: always

    - name: Reload the switch to activate new image
      cisco.ios.ios_command:
        commands:
          - "reload"
      vars:
        ansible_command_timeout: 120
      ignore_errors: yes
