---
- name: Backup running-config from Cisco 9300 to TFTP
  hosts: 192.168.29.164
  gather_facts: no
  connection: network_cli
  collections:
    - cisco.ios

  tasks:
    - name: Save running configuration
      cisco.ios.ios_config:
        backup: yes
        backup_options:
          filename: newbackup.cfg

      register: backup_path

    
