- name: Export tech-support logs to TFTP
  hosts: cisco_stack_switch
  gather_facts: no

  vars:
    tftp_server: "192.168.29.208"
    tech_support_filename: "techsupport.txt"
    tech_support_timeout: 300 # 5 minutes for tech-support generation
    copy_timeout: 300 # allow longer TFTP transfers

  tasks:
    - name: Generate tech-support log
      cisco.ios.ios_command:
        commands:
          - "show tech-support | redirect flash:{{ tech_support_filename }}"
      vars:
        ansible_command_timeout: "{{ tech_support_timeout }}"
      register: tech_output

    - name: Verify tech-support file was created
      cisco.ios.ios_command:
        commands:
          - "dir flash: | include {{ tech_support_filename }}"
      register: file_check

    - name: Display file verification
      debug:
        var: file_check.stdout_lines

    - name: Copy tech-support log to TFTP
      cisco.ios.ios_command:
        commands:
          - command: "copy flash:{{ tech_support_filename }} tftp://{{ tftp_server }}/{{ tech_support_filename }}"
            prompt:
              - "Address or name of remote host"
              - "Destination filename"
            answer:
              - "{{ tftp_server }}"
              - "{{ tech_support_filename }}"
      vars:
        ansible_command_timeout: "{{ copy_timeout }}"
      register: copy_output

    - name: Show transfer result
      debug:
        var: copy_output.stdout_lines

    - name: Post-check | Environment, Power, EtherChannel
      cisco.ios.ios_command:
        commands:
          - show environment all
          - show power inline
          - show etherchannel summary
      register: postcheck_output

    - name: Display Post-check Output
      debug:
        var: postcheck_output.stdout_lines
