---
- name: Backup running-config from Cisco 9300 to TFTP
  hosts: cisco_stack_switch
  gather_facts: no

  tasks:
    - name: Configure NTP, logging and timestamps
      cisco.ios.ios_config:
        lines:
          - ntp server 192.168.29.6 prefer
          - service timestamps log datetime msec localtime show-timezone
          - logging host 192.168.29.6
          - logging trap informational
        save_when: modified
        backup: yes
        backup_options:
          dir_path: /var/lib/awx/panos_backups
          # optionally you can define filename, else default will be used:
          # filename: "{{ inventory_hostname }}_config_{{ ansible_date_time.iso8601 }}.cfg"
      register: copy_out

    - name: Show the backup path
      debug:
        var: copy_out.backup_path
