---
- name: Failover ISP link on Cisco L3 9300
  hosts: "{{ router }}"
  gather_facts: no
  connection: network_cli
  become: yes
  vars:
    primary_iface: "{{ primary_iface }}"
    backup_iface:  "{{ backup_iface }}"
    primary_next_hop: "{{ primary_next_hop }}"
    backup_next_hop:  "{{ backup_next_hop }}"
  tasks:

    - name: Remove old default route via primary
      ios_config:
        lines:
          - no ip route 0.0.0.0 0.0.0.0 {{ primary_next_hop }}
        save_when: modified

    - name: Add default route via backup
      ios_config:
        lines:
          - ip route 0.0.0.0 0.0.0.0 {{ backup_next_hop }}
        save_when: modified

    - name: Send notification back to Splunk (optional)
      uri:
        url: "http://192.168.29.130:8088/services/collector"   # or your Splunk HEC endpoint
        method: POST
        headers:
          Authorization: "Splunk YOUR_HEC_TOKEN"
          Content-Type: "application/json"
        body_format: json
        body:
          event: "ISP failover triggered"
          router: "{{ router }}"
          primary_iface: "{{ primary_iface }}"
          backup_iface: "{{ backup_iface }}"
        validate_certs: no
