---
- name: Upgrade Cisco Catalyst 9300 Switch
  hosts: 192.168.29.164
  gather_facts: no
  connection: network_cli
  vars:
    new_image: "cat9k_iosxe.17.15.03.SPA.bin"
    tftp_server: "192.168.29.22"
    image_path: "flash:/{{ new_image }}"
    boot_system_cmd: "boot system flash:{{ new_image }}"
  tasks:
    - name: Copy new image to flash from TFTP server
      cisco.ios.ios_command:
        commands:
          - command: "copy tftp://{{ tftp_server }}/{{ new_image }} flash:/{{ new_image }}"
            prompt: "Destination filename"
            answer: "{{ new_image }}"
      vars:
        ansible_command_timeout: 1800

    - name: Verify image checksum
      cisco.ios.ios_command:
        commands:
          - "verify /md5 flash:{{ new_image }}"
      vars:
        ansible_command_timeout: 600

    - name: Set boot variable to new image
      cisco.ios.ios_config:
        lines:
          - "{{ boot_system_cmd }}"

    - name: Save running configuration
      cisco.ios.ios_config:
        save_when: always

    - name: Reload the switch to activate new image
      cisco.ios.ios_command:
        commands:
          - "reload"
      vars:
        ansible_command_timeout: 120
      ignore_errors: yes
