---
- name: Upgrade Cisco Catalyst 9300 Switch
  hosts: 192.168.29.164
  gather_facts: no
  connection: network_cli
  vars:
    new_image: "cat9k_iosxe.17.15.03.SPA.bin"
    tftp_server: "192.168.29.22"
    image_path: "flash:/{{ new_image }}"
    boot_system_cmd: "boot system flash:{{ new_image }}"
    mgmt_vrf: "Mgmt-vrf" # Management VRF name
  tasks:
    - name: Check connectivity to TFTP server (via Mgmt VRF)
      cisco.ios.ios_command:
        commands:
          - "ping vrf {{ mgmt_vrf }} {{ tftp_server }} repeat 5"
      register: ping_result

    - name: Display ping result
      ansible.builtin.debug:
        var: ping_result.stdout_lines

    - name: Verify flash space
      cisco.ios.ios_command:
        commands:
          - "show flash: | include bytes"
      register: flash_space

    - name: Display flash space
      ansible.builtin.debug:
        var: flash_space.stdout_lines

    - name: Copy new image to flash from TFTP server (via Mgmt VRF)
      cisco.ios.ios_command:
        commands:
          - command: "copy tftp: flash: vrf {{ mgmt_vrf }}"
            prompt:
              - "Address or name of remote host"
              - "Source filename"
              - "Destination filename"
              - "\\[.*\\]\\?"
            answer:
              - "{{ tftp_server }}"
              - "{{ new_image }}"
              - "{{ new_image }}"
              - "{{ new_image }}"
      vars:
        ansible_command_timeout: 2700


    - name: Set boot variable to new image
      cisco.ios.ios_config:
        lines:
          - "{{ boot_system_cmd }}"

    - name: Save running configuration
      cisco.ios.ios_config:
        save_when: always

    - name: Reload the switch to activate new image
      cisco.ios.ios_command:
        commands:
          - "reload"
      vars:
        ansible_command_timeout: 120
      ignore_errors: yes
