---
- name: Upgrade Cisco Catalyst 9300 to new IOS-XE version
  hosts: 192.168.29.164
  gather_facts: no
  connection: network_cli

  vars:
    upgrade_image: "cat9k_iosxe.17.15.03.SPA.bin"
    tftp_server: "192.168.29.22"
    remote_image_path: "tftp://{{ tftp_server }}/Users/prabhakaran/Downloads/{{ upgrade_image }}"
    bootflash_image: "bootflash:{{ upgrade_image }}"
    expected_version: "17.15.03"
    # Timeout for long-running commands (in seconds)
    ansible_command_timeout: 2700

  tasks:
    - name: Show current IOS-XE version
      cisco.ios.ios_command:
        commands:
          - "show version"
      register: version_out

    - name: Debug current version
      debug:
        msg: "{{ version_out.stdout[0] }}"

    - name: Copy new IOS-XE image to switch via TFTP
      cisco.ios.ios_command:
        commands:
          - "copy {{ remote_image_path }} {{ bootflash_image }}"
        wait_for:
          - "result[0] contains Copy complete"
        retries: 60
        interval: 30
      vars:
        ansible_command_timeout: 1200
      register: copy_out

    - name: Debug copy output
      debug:
        var: copy_out.stdout_lines

    - name: Verify MD5 checksum of the new image (optional)
      cisco.ios.ios_command:
        commands:
          - "verify /md5 {{ bootflash_image }}"
      register: md5_out

    - name: Debug MD5 verify output
      debug:
        var: md5_out.stdout_lines

    - name: Install and activate the new image (install mode)
      cisco.ios.ios_command:
        commands:
          - "install add file {{ bootflash_image }} activate commit"
        prompt:
          - "This operation requires a reload of the system. Do you want to proceed?"
        answer:
          - "y"
        wait_for:
          - "result[0] contains install_add_activate_commit"
        retries: 5
        interval: 60
      register: install_out

    - name: Debug install output
      debug:
        var: install_out.stdout_lines

    - name: Pause for installation to proceed
      pause:
        minutes: 10

    - name: Reload the switch to boot the new image
      cisco.ios.ios_command:
        commands:
          - "reload"
        prompt:
          - "Proceed with reload?"
          - "confirm"
        answer:
          - "\n"
        retries: 3
        interval: 10
      vars:
        ansible_command_timeout: 300

    - name: Wait for switch to come back after reload
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 60
        timeout: 900
      delegate_to: localhost

    - name: Show version after reload
      cisco.ios.ios_command:
        commands:
          - "show version"
      register: post_version

    - name: Debug version after reload
      debug:
        var: post_version.stdout[0]

    - name: Assert that the version is the expected version
      assert:
        that:
          - "'{{ expected_version }}' in post_version.stdout[0]"
        fail_msg: "Upgrade failed: version after reload is not {{ expected_version }}"
        success_msg: "Upgrade succeeded: version is {{ expected_version }}"
