---
- name: Full Cisco 9300 Upgrade via TFTP (Mgmt-vrf)
  # hosts: "{{ target_host | default('192.168.29.164') }}"
  hosts: cisco_stack_switch
  gather_facts: no

  tasks:
    - name: Ping TFTP server via Mgmt-vrf
      cisco.ios.ios_command:
        commands:
          - "ping vrf Mgmt-vrf 192.168.29.208"

    - name: Copy image from TFTP to flash using Mgmt-vrf
      cisco.ios.ios_command:
        commands:
          - command: "copy tftp://192.168.29.208/cat9k_iosxe.17.12.06.SPA.bin flash:cat9k_iosxe.17.12.06.SPA.bin vrf Mgmt-vrf"
            prompt: "Destination filename"
            answer: "cat9k_iosxe.17.12.06.SPA.bin"
      register: copy_output
      vars:
        ansible_command_timeout: 600

    - name: Show copy output
      debug:
        var: copy_output.stdout_lines

    - name: Verify image exists in flash
      cisco.ios.ios_command:
        commands:
          - "dir flash:cat9k_iosxe.17.12.06.SPA.bin"
      register: dir_output

    - name: Show dir result
      debug:
        var: dir_output.stdout_lines

    - name: Set boot variable to packages.conf (Install mode)
      cisco.ios.ios_config:
        lines:
          - no boot system
          - "boot system flash:packages.conf"

    - name: Disable ignore startup-config on 9300  
      cisco.ios.ios_config:  
        lines:  
          - no system ignore startupconfig switch all
          - no boot manual 


    - name: Save running-config
      cisco.ios.ios_command:
        commands:
          - write memory
      vars:
        ansible_command_timeout: 120


    - name: Copy image from TFTP to flash using Mgmt-vrf
      cisco.ios.ios_command:
        commands:
          - command: "copy tftp://192.168.29.208/cat9k_iosxe.17.12.06.SPA.bin flash:cat9k_iosxe.17.12.06.SPA.bin vrf Mgmt-vrf"
            prompt: "Destination filename"
            answer: "cat9k_iosxe.17.12.06.SPA.bin"
      register: copy_output
      vars:
        ansible_command_timeout: 600




    - name: Run install add/activate/commit to convert to install mode
      cisco.ios.ios_command:
        commands:
          - command: "install add file flash:cat9k_iosxe.17.12.06.SPA.bin activate commit"
            prompt:
              - "Do you want to proceed"
              - "This operation requires a reload"
              - "Proceed with reload"
            answer:
              - "y"
              - "y"
              - "y"
      register: install_output
      vars:
        ansible_command_timeout: 1200

    - name: Wait for device to become reachable after reload
      wait_for_connection:
        timeout: 900
        delay: 30
        sleep: 5

    - name: Verify device is back (show version)
      cisco.ios.ios_command:
        commands:
          - "show version"
      register: boot_output

    - name: Show boot verification
      debug:
        var: boot_output.stdout_lines
