---
- name: Backup running-config from Cisco 9300 to TFTP
  hosts: 192.168.29.164
  gather_facts: no
  connection: network_cli
  collections:
    - cisco.ios

  tasks:
    - name: Save running configuration
      cisco.ios.ios_config:
        backup: yes

      register: backup_result

    - name: Show result of backup
      debug:
        var: backup_result.stdout_lines
