---
- name: Backup running-config from Cisco 9300 to TFTP
  hosts: 192.168.29.164
  gather_facts: no

  tasks:
    - name: Configure NTP, logging and timestamps
      cisco.ios.ios_config:
        lines:
          - ntp server 192.168.29.5 prefer
          - service timestamps log datetime msec localtime show-timezone
          - logging host 192.168.29.5
          - logging trap informational
        save_when: modified
        backup: yes
        register: copy_out
  - name: Show the backup path
    debug:
      var: copy_output.backup_path
      
