---
- name: Backup running-config from Cisco 9300 to TFTP
  hosts: cisco_stack_switch
  gather_facts: no

  tasks:
    - name: Configure NTP, logging and timestamps
      cisco.ios.ios_config:
        lines:
          - ntp server 192.168.29.3 prefer
          - service timestamps log datetime msec localtime show-timezone
          - logging host 192.168.29.3
          - logging trap informational
        save_when: modified
        backup: yes
        backup_options:
          filename: newbackup1.cfg
          dir_path: /var/lib/awx/projects
      register: backup_location

    - name: Summary for host
      ansible.builtin.debug:
        msg: >
          Backup is stored at {{ backup_location.backup_path }}
--- End of Backup ---
