---
- name: Create address objects
  hosts: "firewalls"
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Create source address object
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ device }}"
        name: "source-server1"
        value: "192.168.120.81/32"
        description: "Address object 1 from Ansible"
      

    - name: Create destination address object
      paloaltonetworks.panos.panos_address_object:
        provider: "{{ device }}"
        name: "destination-server1"
        value: "192.168.80.51/32"
        description: "Address object 2 from Ansible"

    - name: Commit candidate configuration
      paloaltonetworks.panos.panos_commit_firewall:
        provider: "{{ device }}"
