---
- name: Audit Palo Alto Security Rules for Missing Profiles / Description / Decryption
  hosts: "PRODUCTIONFIREWALL"
  connection: local
  gather_facts: no

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"
    expected_dns_primary: "{{ dns_primary | default('8.8.8.8') }}"
    expected_dns_secondary: "{{ dns_secondary | default('192.168.29.5') }}"
    expected_ntp_primary: "{{ ntp_primary | default('1.1.1.1') }}"
    expected_ntp_secondary: "{{ ntp_secondary | default('2.2.2.3') }}"
    expected_syslog_ip: "{{ syslog_ip | default('192.168.29.3') }}"
    required_profiles:
      - antivirus
      - vulnerability
      - spyware
      - url_filtering
      - file_blocking

  collections:
    - paloaltonetworks.panos

  tasks:

    - name: Gather all security rules
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        state: gathered
        gathered_filter: "*"
      register: sec_rules

    - name: Gather running configuration
      paloaltonetworks.panos.panos_facts:
        provider: "{{ device }}"
        gather_subset: ["config"]
      register: pan_config

    - name: Filter any-any insecure rules (source=any, dest=any, service=any)
      set_fact:
        any_any_insecure_rules: >-
          {{
            (sec_rules.gathered | default([]))
            | selectattr('source_ip', 'equalto', ['any'])
            | selectattr('destination_ip', 'equalto', ['any'])
            | selectattr('service', 'equalto', ['any'])
            | selectattr('source_zone', 'equalto', ['any'])
            | selectattr('destination_zone', 'equalto', ['any'])
            | list
          }}

    - name: Filter rules missing description
      set_fact:
        rules_missing_description: >-
          {{
            (sec_rules.gathered | default([]))
            | selectattr('description', 'equalto', None)
            | list
          }}

    - name: Filter rules that use a specific source_user (not 'any')
      set_fact:
        user_based_rules: >-
          {{
            (sec_rules.gathered | default([]))
            | selectattr('source_user', 'defined')
            | rejectattr('source_user', 'equalto', ['any'])
            | list
          }}

    - name: Get all decryption rules
      paloaltonetworks.panos.panos_decryption_rule:
        provider: "{{ device }}"
        state: gathered
        gathered_filter: "*"
      register: decryption_rules

    - name: Filter decryption rules with action = decrypt or decrypt-and-forward
      set_fact:
        decrypt_rules: >-
          {{
            (decryption_rules.decryption_rules | default([]))
            | selectattr('action', 'in', ['decrypt', 'decrypt-and-forward'])
            | list
          }}

    - name: Filter security rules where any required profile is missing
      set_fact:
        rules_missing_profiles: >-
          {{
            (sec_rules.gathered | default([]))
            | selectattr('group_profile', 'equalto', None)
            | selectattr('antivirus', 'equalto', None)
            | selectattr('vulnerability', 'equalto', None)
            | selectattr('spyware', 'equalto', None)
            | selectattr('url_filtering', 'equalto', None)
            | selectattr('file_blocking', 'equalto', None)
            | list
          }}

    - name: Find security rules where logging is not enabled
      set_fact:
        rules_without_logging: >-
          {{
            (sec_rules.gathered | default([]))
            | selectattr('log_start', 'equalto', False)
            | selectattr('log_end', 'equalto', False)
            | list
          }}

    - name: Run readiness checks (NTP sync, HA, content version)
      panos_readiness_checks:
        checks:
        provider: "{{ device }}"
          - ntp_sync
          - ha
          - content_version
        force_fail: false
      register: readiness
      ignore_errors: yes


    - name: Print rules without description
      ansible.builtin.debug:
        msg: |
          The following security rules are missing descriptions:
          {% for rule in rules_missing_description %}
          - {{ rule.rule_name | default(rule.name) }}
          {% else %}
          (None found)
          {% endfor %}

    - name: Print insecure any-any rules
      ansible.builtin.debug:
        msg: |
          Insecure any-any rules:
          {% for rule in any_any_insecure_rules %}
          - {{ rule.rule_name | default(rule.name) }}
          {% else %}
          (None found)
          {% endfor %}

    - name: Print user-based rules
      ansible.builtin.debug:
        msg: |
          Security rules with specific source_user:
          {% for rule in user_based_rules %}
          - {{ rule.rule_name | default(rule.name) }} → source_user: {{ rule.source_user }}
          {% else %}
          (No user-based security rules found)
          {% endfor %}

    - name: Print decrypt rules
      ansible.builtin.debug:
        msg: |
          Decryption rules (action = decrypt or decrypt-and-forward):
          {% for rule in decrypt_rules %}
          - {{ rule.name }} → action: {{ rule.action }}, decryption_type: {{ rule.decryption_type }}
          {% else %}
          (No decrypt rules found)
          {% endfor %}

    - name: Print rules missing required profile(s)
      ansible.builtin.debug:
        msg: |
          Security rules missing one or more mandatory profiles:
          {% for rule in rules_missing_profiles %}
          - {{ rule.rule_name | default(rule.name) }}:
            * antivirus = {{ rule.antivirus | default('None') }}
            * vulnerability = {{ rule.vulnerability | default('None') }}
            * spyware = {{ rule.spyware | default('None') }}
            * url_filtering = {{ rule.url_filtering | default('None') }}
            * file_blocking = {{ rule.file_blocking | default('None') }}
          {% else %}
          (All rules have at least one of the required profiles or a profile group.)
          {% endfor %}

    - name: Report security rules missing logging
      ansible.builtin.debug:
        msg: |
          The following security rules do NOT have logging enabled (neither start nor end):
          {% for rule in rules_without_logging %}
          - {{ rule.rule_name | default(rule.name) }}: log_start={{ rule.log_start }}, log_end={{ rule.log_end }}
          {% else %}
          (All rules have logging on at least at start or end.)
          {% endfor %}

    - name: Debug readiness check results
      debug:
        var: readiness.response

    - name: Build compliance status message
      set_fact:
        compliance_status: |
          Host: {{ inventory_hostname }}
            NTP sync        : {{ readiness.response.ntp_sync.state | default(false) | ternary('PASS','FAIL') }} ({{ readiness.response.ntp_sync.reason | default('') }})
            HA / config sync: {{ readiness.response.ha.state | default(false) | ternary('PASS','FAIL') }} ({{ readiness.response.ha.reason | default('') }})
            Content version : {{ readiness.response.content_version.state | default(false) | ternary('PASS','FAIL') }} ({{ readiness.response.content_version.reason | default('') }})

    - name: Show compliance status
      debug:
        msg: "{{ compliance_status }}"

  
