---
- name: Find security rules without description
  hosts: "{{ hosts | default('PRODUCTIONFIREWALL') }}"
  connection: local
  gather_facts: no

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Gather all security rules
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        state: gathered
        gathered_filter: "*"  # fetch all rules :contentReference[oaicite:0]{index=0}
      register: sec_rules


    - name: Filter any-any insecure rules (source=any, dest=any, service=any)
      ansible.builtin.set_fact:
        any_any_insecure_rules: >-
          {{
            (sec_rules.gathered | default([]))
            | selectattr('source_ip', 'equalto', ['any'])
            | selectattr('destination_ip', 'equalto', ['any'])
            | selectattr('service', 'equalto', ['any'])
            | selectattr('source_zone', 'equalto', ['any'])
            | selectattr('destination_zone', 'equalto', ['any'])
            | list
          }}


    - name: Filter rules missing description
      ansible.builtin.set_fact:
        rules_missing_description: >-
          {{
            (sec_rules.gathered | default([]))
            | selectattr('description', 'equalto', None)
            | list
          }}


    - name: Print rules without description
      ansible.builtin.debug:
        msg: |
          The following security rules are missing a description and audit comment:
          {% for rule in rules_missing_description %}
            - {{ rule.rule_name | default(rule.name) }}
          {% else %}
            (None found)
          {% endfor %}



    - name: Report insecure any-any rules
      ansible.builtin.debug:
        msg: |
          Insecure any-any rules (source=any, dest=any, service=any):
          {% for rule in any_any_insecure_rules %}
            - {{ rule.rule_name | default(rule.name) }}
          {% else %}
            (None found)
          {% endfor %}
