---
- name: Audit Palo Alto Security Rules for Missing Profiles / Description / Decryption  
  hosts: "{{ hosts | default('PRODUCTIONFIREWALL') }}"  
  connection: local  
  gather_facts: no  

  vars:  
    device:  
      ip_address: "{{ ip_address }}"  
      username: "{{ username }}"  
      password: "{{ password }}"  
    expected_dns_primary: "{{ dns_primary | default('8.8.8.8') }}"
    expected_dns_secondary: "{{ dns_secondary | default('192.168.29.3') }}"
    expected_ntp_primary: "{{ ntp_primary | default('10.1.1.10') }}"
    expected_ntp_secondary: "{{ ntp_secondary | default('10.1.1.11') }}"
    expected_syslog_ip: "{{ syslog_ip | default('192.168.29.3') }}"  

    required_profiles:  
      - antivirus  
      - vulnerability  
      - spyware  
      - url_filtering  
      - file_blocking  

  collections:  
    - paloaltonetworks.panos  

  tasks:  
    - name: Gather all security rules  
      paloaltonetworks.panos.panos_security_rule:  
        provider: "{{ device }}"  
        state: gathered  
        gathered_filter: "*"  
      register: sec_rules  

    - name: Gather running configuration
      paloaltonetworks.panos.panos_facts:
        provider: "{{ device }}"
        gather_subset: ["config"]
      register: pan_config

    - name: Ensure configuration XML retrieved
      ansible.builtin.assert:
        that:
          - pan_config.ansible_facts.ansible_net_config is defined
          - pan_config.ansible_facts.ansible_net_config | length > 0
        fail_msg: "Failed to retrieve configuration XML from firewall – cannot proceed."

    - name: Set cfg_xml fact
      ansible.builtin.set_fact:
        cfg_xml: "{{ pan_config.ansible_facts.ansible_net_config }}"

    - name: Extract configured DNS servers
      ansible.builtin.set_fact:
        dns_servers: >-
          {{
            cfg_xml
            | regex_findall('<dns\\-server>\\s*<entry>\\s*<ip>([0-9\\.]+)</ip>\\s*</entry>')
          }}

    - name: Set DNS primary/secondary values
      ansible.builtin.set_fact:
        dns_primary_current: "{{ dns_servers.0 | default('') }}"
        dns_secondary_current: "{{ dns_servers.1 | default('') }}"

    - name: Extract configured NTP servers
      ansible.builtin.set_fact:
        ntp_servers: >-
          {{
            cfg_xml
            | regex_findall('<ntp\\-server>\\s*<primary>([0-9\\.]+)</primary>.*?<secondary>([0-9\\.]+)</secondary>')
          }}

    - name: Set NTP primary/secondary values
      ansible.builtin.set_fact:
        ntp_primary_current: "{{ ntp_servers.0 | default('') }}"
        ntp_secondary_current: "{{ ntp_servers.1 | default('') }}"

    - name: Extract syslog server IP
      ansible.builtin.set_fact:
        syslog_current_ip: >-
          {{
            (cfg_xml | regex_findall('<syslog\\-server>\\s*<entry>\\s*<ip>([0-9\\.]+)</ip>')) 
            | first | default('')
          }}

    - name: Filter any-any insecure rules (source=any, dest=any, service=any)  
      set_fact:  
        any_any_insecure_rules: >-  
          {{  
            (sec_rules.gathered | default([]))  
            | selectattr('source_ip', 'equalto', ['any'])  
            | selectattr('destination_ip', 'equalto', ['any'])  
            | selectattr('service', 'equalto', ['any'])  
            | selectattr('source_zone', 'equalto', ['any'])  
            | selectattr('destination_zone', 'equalto', ['any'])  
            | list  
          }}  

    - name: Filter rules missing description  
      set_fact:  
        rules_missing_description: >-  
          {{  
            (sec_rules.gathered | default([]))  
            | selectattr('description', 'equalto', None)  
            | list  
          }}  

    - name: Filter rules that use a specific source_user (i.e. not 'any')  
      set_fact:  
        user_based_rules: >-  
          {{  
            (sec_rules.gathered | default([]))  
            | selectattr('source_user', 'defined')  
            | rejectattr('source_user', 'equalto', ['any'])  
            | list  
          }}  

    - name: Get all decryption rules  
      paloaltonetworks.panos.panos_decryption_rule:  
        provider: "{{ device }}"  
        state: gathered  
        gathered_filter: "*"  
      register: decryption_rules  

    - name: Filter decryption rules with action = decrypt or decrypt-and-forward  
      set_fact:  
        decrypt_rules: >-  
          {{  
            (decryption_rules.decryption_rules | default([]))  
            | selectattr('action', 'in', ['decrypt', 'decrypt-and-forward'])  
            | list  
          }}  

    - name: Filter security rules where any required profile is missing
      set_fact:
        rules_missing_profiles: >-
          {{
            (sec_rules.gathered | default([]))
            | selectattr('group_profile', 'equalto', None)
            | selectattr('antivirus', 'equalto', None)
            | selectattr('vulnerability', 'equalto', None)
            | selectattr('spyware', 'equalto', None)
            | selectattr('url_filtering', 'equalto', None)
            | selectattr('file_blocking', 'equalto', None)
            | list
          }}

    - name: Find security rules where logging is not enabled
      set_fact:
        rules_without_logging: >-
          {{
            (sec_rules.gathered | default([]))
            | selectattr('log_start', 'equalto', False)
            | selectattr('log_end', 'equalto', False)
            | list
          }}
  

    - name: Print rules without description  
      ansible.builtin.debug:  
        msg: |  
          The following security rules are missing descriptions:  
          {% for rule in rules_missing_description %}  
          - {{ rule.rule_name | default(rule.name) }}  
          {% else %}  
          (None found)  
          {% endfor %}  

    - name: Print insecure any-any rules  
      ansible.builtin.debug:  
        msg: |  
          Insecure any-any rules:  
          {% for rule in any_any_insecure_rules %}  
          - {{ rule.rule_name | default(rule.name) }}  
          {% else %}  
          (None found)  
          {% endfor %}  

    - name: Print user-based rules  
      ansible.builtin.debug:  
        msg: |  
          Security rules with specific source_user:  
          {% for rule in user_based_rules %}  
          - {{ rule.rule_name | default(rule.name) }} → source_user: {{ rule.source_user }}  
          {% else %}  
          (No user-based security rules found)  
          {% endfor %}  

    - name: Print decrypt rules  
      ansible.builtin.debug:  
        msg: |  
          Decryption rules (action = decrypt or decrypt-and-forward):  
          {% for rule in decrypt_rules %}  
          - {{ rule.name }} → action: {{ rule.action }}, decryption_type: {{ rule.decryption_type }}  
          {% else %}  
          (No decrypt rules found)  
          {% endfor %}  

    - name: Print rules missing required profile(s)  
      ansible.builtin.debug:  
        msg: |  
          Security rules missing one or more mandatory profiles:  
          {% for rule in rules_missing_profiles %}  
          - {{ rule.rule_name | default(rule.name) }}:  
            * antivirus = {{ rule.antivirus | default('None') }}  
            * vulnerability = {{ rule.vulnerability | default('None') }}  
            * spyware = {{ rule.spyware | default('None') }}  
            * url_filtering = {{ rule.url_filtering | default('None') }}  
            * file_blocking = {{ rule.file_blocking | default('None') }}  
          {% else %}  
          (All rules have at least one of the required profiles or a profile group.)  
          {% endfor %}  

    - name: Report security rules missing logging
      ansible.builtin.debug:
       msg: |
         The following security rules do NOT have logging enabled (neither start nor end):
         {% for rule in rules_without_logging %}
         - {{ rule.rule_name | default(rule.name) }}: log_start={{ rule.log_start }}, log_end={{ rule.log_end }}
         {% else %}
         (All rules have logging on at least at start or end.)
         {% endfor %}

    - name: Compute compliance booleans
      ansible.builtin.set_fact:
        dns_primary_ok: "{{ dns_primary_current == expected_dns_primary }}"
        dns_secondary_ok: "{{ dns_secondary_current == expected_dns_secondary }}"
        ntp_primary_ok: "{{ ntp_primary_current == expected_ntp_primary }}"
        ntp_secondary_ok: "{{ ntp_secondary_current == expected_ntp_secondary }}"
        syslog_ok: "{{ syslog_current_ip == expected_syslog_ip }}"

   - name: Build final consolidated report
      ansible.builtin.set_fact:
        compliance_report:
          dns_ntp_syslog:
            dns_primary: "{{ dns_primary_current }} : {{ 'COMPLIANT' if dns_primary_ok else 'NON-COMPLIANT' }}"
            dns_secondary: "{{ dns_secondary_current }} : {{ 'COMPLIANT' if dns_secondary_ok else 'NON-COMPLIANT' }}"
            ntp_primary: "{{ ntp_primary_current }} : {{ 'COMPLIANT' if ntp_primary_ok else 'NON-COMPLIANT' }}"
            ntp_secondary: "{{ ntp_secondary_current }} : {{ 'COMPLIANT' if ntp_secondary_ok else 'NON-COMPLIANT' }}"
            syslog_server: "{{ syslog_current_ip }} : {{ 'COMPLIANT' if syslog_ok else 'NON-COMPLIANT' }}"

