---
- name: Audit Palo Alto Security Rules for Missing Profiles / Description / Decryption  
  hosts: "{{ hosts | default('PRODUCTIONFIREWALL') }}"  
  connection: local  
  gather_facts: no  

  vars:  
    device:  
      ip_address: "{{ ip_address }}"  
      username: "{{ username }}"  
      password: "{{ password }}"  

    required_profiles:  
      - antivirus  
      - vulnerability  
      - spyware  
      - url_filtering  
      - file_blocking  

  collections:  
    - paloaltonetworks.panos  

  tasks:  
    - name: Gather all security rules  
      paloaltonetworks.panos.panos_security_rule:  
        provider: "{{ device }}"  
        state: gathered  
        gathered_filter: "*"  
      register: sec_rules  

    - name: Filter any-any insecure rules (source=any, dest=any, service=any)  
      set_fact:  
        any_any_insecure_rules: >-  
          {{  
            (sec_rules.gathered | default([]))  
            | selectattr('source_ip', 'equalto', ['any'])  
            | selectattr('destination_ip', 'equalto', ['any'])  
            | selectattr('service', 'equalto', ['any'])  
            | selectattr('source_zone', 'equalto', ['any'])  
            | selectattr('destination_zone', 'equalto', ['any'])  
            | list  
          }}  

    - name: Filter rules missing description  
      set_fact:  
        rules_missing_description: >-  
          {{  
            (sec_rules.gathered | default([]))  
            | selectattr('description', 'equalto', None)  
            | list  
          }}  

    - name: Filter rules that use a specific source_user (i.e. not 'any')  
      set_fact:  
        user_based_rules: >-  
          {{  
            (sec_rules.gathered | default([]))  
            | selectattr('source_user', 'defined')  
            | rejectattr('source_user', 'equalto', ['any'])  
            | list  
          }}  

    - name: Get all decryption rules  
      paloaltonetworks.panos.panos_decryption_rule:  
        provider: "{{ device }}"  
        state: gathered  
        gathered_filter: "*"  
      register: decryption_rules  

    - name: Filter decryption rules with action = decrypt or decrypt-and-forward  
      set_fact:  
        decrypt_rules: >-  
          {{  
            (decryption_rules.decryption_rules | default([]))  
            | selectattr('action', 'in', ['decrypt', 'decrypt-and-forward'])  
            | list  
         
