---
- name: Find security rules without description or audit comment
  hosts: "{{ hosts | default('PRODUCTIONFIREWALL') }}"
  connection: local
  gather_facts: no

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Gather all security rules (with facts)
      paloaltonetworks.panos.panos_security_rule_facts:
        provider: "{{ device }}"
      register: sec_rules_facts

    - name: Filter rules missing description or audit_comment
      ansible.builtin.set_fact:
        rules_missing_meta: >-
          {{
            sec_rules_facts.rules
            | selectattr('spec', 'defined')
            | selectattr('spec.description', 'equalto', None)
            | list
            | union(
                sec_rules_facts.rules
                | selectattr('spec', 'defined')
                | selectattr('spec.audit_comment', 'not defined')
                | list
              )
          }}

    - name: Print rules without description or audit comment
      ansible.builtin.debug:
        msg: |
          The following security rules are missing description or audit_comment:
          {% for rule in rules_missing_meta %}
            - {{ rule.name }}
          {% endfor %}
