---
- name: Find security rules without description or audit comment
  hosts: "{{ hosts | default('PRODUCTIONFIREWALL') }}"
  connection: local
  gather_facts: no

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Gather all security rules
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        state: gathered
        gathered_filter: "*"          # Use gathered_filter to fetch all rules :contentReference[oaicite:1]{index=1}
      register: sec_rules

    - name: Filter rules missing description or audit_comment
      ansible.builtin.set_fact:
        rules_missing_meta: >-
          {{
            sec_rules.resources
            | selectattr('description', 'equalto', None)
            | union(
                sec_rules.resources
                | selectattr('audit_comment', 'is-none')
              )
            | list
          }}

    - name: Print rules without description or audit comment
      ansible.builtin.debug:
        msg: |
          The following security rules are missing description or audit_comment:
          {% for rule in rules_missing_meta %}
            - {{ rule.rule_name }}
          {% endfor %}
