---
- name: FortiGate HA Pre-Upgrade Backup
  hosts: fortigates
  gather_facts: no
  tasks:
    - name: Backup current FortiGate configuration (global) before upgrade
      fortinet.fortios.fortios_system_config_backup_restore:
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        vdom: "{{ vdom }}"
        backup: yes
        filename: "backup_{{ inventory_hostname }}_pre_upgrade_{{ ansible_date_time.iso8601 }}.conf"
      register: cfg_backup

    - name: Save backup content locally on Ansible controller
      copy:
        content: "{{ cfg_backup }}"
        dest: "./backups/{{ inventory_hostname }}_pre_upgrade_{{ ansible_date_time.iso8601 }}.conf"

- name: Trigger Firmware upgrade of HA cluster via FortiManager
  hosts: fortimanager
  gather_facts: no
  collections:
    - fortinet.fortimanager
  vars:
    adom: "Root"                   # adjust as per your ADOM name
    devprof: "FGT_Devices"         # adjust as per your device profile
    firmware_file: "FGT-VM64-KVM-v7.2.6.out"   # adjust as per your target firmware
    target_device: "fgt-fw1"       # FMG’s device name for the HA cluster
  tasks:
    - name: Push firmware upgrade to FortiGate HA cluster
      fmgr_um_image_upgrade_ext:
        adom: "{{ adom }}"
        device: "{{ target_device }}"
        image: "{{ firmware_file }}"
      register: upgrade_result

    - name: Show result of firmware upgrade push
      debug:
        var: upgrade_result
