---
- name: Gather security rules
  hosts: "PRODUCTIONFIREWALL"
  connection: local

  vars:
    device:
      ip_address: "192.168.29.221"
      username: "naveen"
      password: "Naveen@vfm2025!"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Get all security rules
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        gathered_filter: "*"
        state: gathered
      register: sec_rules

    - name: Output
      ansible.builtin.debug:
        msg: "{{ sec_rules }}"
