---
- name: Gather and report system info
  hosts: "PRODUCTIONFIREWALL"
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"
    report_output_dir: "{{ playbook_dir }}/reports"
    report_filename: "{{ inventory_hostname }}-system-info.pdf"
    report_output_path: "{{ report_output_dir }}/{{ report_filename }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Gather facts for device
      # Collect device information including the serial number
      paloaltonetworks.panos.panos_facts:
        provider: "{{ device }}"

    - name: Capture serial number for reporting
      ansible.builtin.set_fact:
        device_serial_number: "{{ ansible_facts['net_serial'] | default('') }}"

    - name: Ensure serial number was collected
      ansible.builtin.fail:
        msg: "Serial number was not found in gathered facts."
      when: device_serial_number | length == 0

    - name: Ensure report output directory exists
      ansible.builtin.file:
        path: "{{ report_output_dir }}"
        state: directory
        mode: "0755"
      delegate_to: localhost

    - name: Generate PDF report for device
      ansible.builtin.command:
        argv:
          - python3
          - reporting/sys_info_report.py
          - "--serial"
          - "{{ device_serial_number }}"
          - "--host"
          - "{{ inventory_hostname }}"
          - "--output"
          - "{{ report_output_path }}"
        chdir: "{{ playbook_dir }}"
      delegate_to: localhost
      register: report_generation
      changed_when: report_generation.rc == 0

    - name: Gather report file details
      ansible.builtin.stat:
        path: "{{ report_output_path }}"
      delegate_to: localhost
      register: sys_info_pdf_stat

    - name: Upload PDF as Controller job artifact
      ansible.builtin.uri:
        url: "{{ tower_url | default(lookup('env', 'TOWER_HOST')) }}/api/v2/jobs/{{ tower_job_id }}/artifacts/"
        method: POST
        user: "{{ tower_username | default(lookup('env', 'TOWER_USERNAME')) }}"
        password: "{{ tower_password | default(lookup('env', 'TOWER_PASSWORD')) }}"
        force_basic_auth: yes
        validate_certs: no
        body_format: form-multipart
        body:
          file:
            content: "{{ lookup('file', report_output_path, lstrip=False, rstrip=False) | b64encode }}"
            filename: "{{ report_filename }}"
        status_code: [200, 201]
      delegate_to: localhost
      register: sys_info_report_upload
      when: tower_job_id is defined

    - name: Publish download link in job artifact metadata
      ansible.builtin.set_stats:
        data:
          sys_info_report:
            filename: "{{ report_filename }}"
            download_url: "{{ sys_info_report_upload.json.file | default(sys_info_report_upload.json.download_url | default('')) }}"
            size_bytes: "{{ sys_info_pdf_stat.stat.size }}"
        per_host: false

    - name: Report PDF location
      ansible.builtin.debug:
        msg:
          - "System info report saved to {{ report_output_path }}"
          - "Report size: {{ sys_info_pdf_stat.stat.size }} bytes"
          - "Download URL: {{ sys_info_report_upload.json.file | default(sys_info_report_upload.json.download_url | default('Unavailable')) }}"
      delegate_to: localhost
