---
- name: PAN-OS HA Content and Software Upgrade with Config Backup
  hosts: "{{ hosts | default('PA-HA') }}"
  connection: local
  gather_facts: false

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

    backup_directory: "{{ lookup('env', 'PANOS_BACKUP_DIR') | default('/runner/backups', true) }}"
    backup_filename: "{{ backup_directory }}/{{ inventory_hostname | default('pa-fw') }}-running-config.xml"

    reboot_between_steps: true
    quiet_polling: true

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Validate upgrade_path is provided
      ansible.builtin.assert:
        that:
          - upgrade_path is defined
          - upgrade_path | length > 0
        fail_msg: 'You must provide -e upgrade_path=''["10.2.3","10.2.4"]'''
      run_once: true

    - name: Gather HA and system facts
      paloaltonetworks.panos.panos_facts:
        provider: "{{ device }}"
        gather_subset: ["system", "ha"]
      register: ha_facts

    - name: Record HA snapshot for {{ inventory_hostname }}
      ansible.builtin.set_fact:
        ha_runtime:
          inventory_hostname: "{{ inventory_hostname }}"
          hostname: "{{ ha_facts.ansible_facts.ansible_net_hostname }}"
          serial: "{{ ha_facts.ansible_facts.ansible_net_serialnum | default('unknown') }}"
          ha_enabled: "{{ (ha_facts.ansible_facts.ansible_net_ha_enabled | default(false)) | bool }}"
          ha_mode: "{{ (ha_facts.ansible_facts.ansible_net_ha_localmode | default('unknown')) | lower }}"
          ha_initial_role: "{{ (ha_facts.ansible_facts.ansible_net_ha_localstate | default('unknown')) | lower }}"
          ha_group_id: "{{ ha_facts.ansible_facts.ansible_net_ha_group_id | default('1') }}"

    - name: Consolidate HA topology view
      run_once: true
      delegate_to: localhost
      delegate_facts: true
      vars:
        ha_view: "{{ ansible_play_hosts_all | map('extract', hostvars, 'ha_runtime') | list }}"
      block:
        - name: Validate HA pair is active/passive and healthy
          ansible.builtin.assert:
            that:
              - ha_view | length == 2
              - (ha_view | map(attribute='ha_enabled') | min)
              - (ha_view | map(attribute='ha_mode') | unique) == ['active-passive']
              - (ha_view | selectattr('ha_initial_role', 'equalto', 'active') | list | length) == 1
              - (ha_view | selectattr('ha_initial_role', 'equalto', 'passive') | list | length) == 1
            fail_msg: "Playbook currently supports exactly two nodes in active/passive HA."
        - name: Persist HA role ownership
          ansible.builtin.set_fact:
            ha_topology: "{{ ha_view }}"
            ha_active_host: "{{ (ha_view | selectattr('ha_initial_role', 'equalto', 'active') | first).inventory_hostname }}"
            ha_passive_host: "{{ (ha_view | selectattr('ha_initial_role', 'equalto', 'passive') | first).inventory_hostname }}"

    - name: Mark initial HA role flags
      ansible.builtin.set_fact:
        is_initial_active: "{{ ha_runtime.ha_initial_role == 'active' }}"
        is_initial_passive: "{{ ha_runtime.ha_initial_role == 'passive' }}"

    - name: Ensure device is ready before content upgrade
      paloaltonetworks.panos.panos_check:
        provider: "{{ device }}"
      register: ready_check
      until: ready_check is not failed and ready_check.msg == 'Device is ready.'
      retries: 10
      delay: 10

    - name: Refresh content update index
      paloaltonetworks.panos.panos_op:
        provider: "{{ device }}"
        cmd: "request content upgrade check"

    - name: Download latest content update
      paloaltonetworks.panos.panos_op:
        provider: "{{ device }}"
        cmd: "request content upgrade download latest"
      register: content_download

    - name: Extract job ID for content download
      ansible.builtin.set_fact:
        content_download_jobid: "{{ content_download.stdout_xml | default('') | regex_search('<job>(\\d+)</job>', '\\1') | first | default('') }}"

    - name: Wait for content download job to complete
      paloaltonetworks.panos.panos_op:
        provider: "{{ device }}"
        cmd: "<show><jobs><id>{{ content_download_jobid }}</id></jobs></show>"
        cmd_is_xml: true
      register: content_download_result
      until: content_download_result.stdout_xml is search('<status>FIN</status>')
      retries: 300
      delay: 10
      failed_when: content_download_result.stdout_xml is search('<result>FAIL</result>')
      when: content_download_jobid | length > 0
      no_log: true

    - name: Install latest content update
      paloaltonetworks.panos.panos_op:
        provider: "{{ device }}"
        cmd: "request content upgrade install version latest"
      register: content_install

    - name: Extract job ID for content install
      ansible.builtin.set_fact:
        content_install_jobid: "{{ content_install.stdout_xml | default('') | regex_search('<job>(\\d+)</job>', '\\1') | first | default('') }}"

    - name: Wait for content install job to complete
      paloaltonetworks.panos.panos_op:
        provider: "{{ device }}"
        cmd: "<show><jobs><id>{{ content_install_jobid }}</id></jobs></show>"
        cmd_is_xml: true
      register: content_install_result
      until: >
        content_install_result.stdout_xml is search('<status>FIN</status>') or
        content_install_result.stdout_xml is search('<status>FAIL</status>')
      retries: 300
      delay: 10
      failed_when: >
        (content_install_result.stdout_xml is search('<status>FIN</status>') and
         content_install_result.stdout_xml is search('<result>FAIL</result>')) or
        content_install_result.stdout_xml is search('<status>FAIL</status>')
      when: content_install_jobid | length > 0
      no_log: true

    - name: Wait for device readiness after content install
      paloaltonetworks.panos.panos_check:
        provider: "{{ device }}"
      register: ready_after_content
      until: ready_after_content is not failed and ready_after_content.msg == 'Device is ready.'
      retries: 60
      delay: 15
      no_log: true

    - name: Backup running configuration
      paloaltonetworks.panos.panos_export:
        provider: "{{ device }}"
        category: configuration
        filename: "{{ backup_filename }}"
        create_directory: true

    - name: Disable config sync
      paloaltonetworks.panos.panos_ha:
        provider: "{{ device }}"
        state: present
        ha_config_sync: false

    - name: Upgrade staged PAN-OS versions on initial passive firewall
      ansible.builtin.include_tasks: tasks/upgrade_step_v2.yml
      loop: "{{ upgrade_path }}"
      loop_control:
        label: "{{ item }}"
      vars:
        version_item: "{{ item }}"
      when: is_initial_passive

    - name: Suspend initial active firewall to trigger failover
      paloaltonetworks.panos.panos_op:
        provider: "{{ device }}"
        cmd: "request high-availability state suspend"
      when: is_initial_active

    - name: Wait for passive peer to assume active role
      paloaltonetworks.panos.panos_active_in_ha:
        provider: "{{ device }}"
      register: passive_now_active
      until: passive_now_active.response.active | default(false)
      retries: 40
      delay: 15
      when: inventory_hostname == hostvars['localhost'].ha_passive_host

    - name: Upgrade staged PAN-OS versions on originally active firewall
      ansible.builtin.include_tasks: tasks/upgrade_step_v2.yml
      loop: "{{ upgrade_path }}"
      loop_control:
        label: "{{ item }}"
      vars:
        version_item: "{{ item }}"
      when: is_initial_active

    - name: Bring suspended firewall back to functional state
      paloaltonetworks.panos.panos_op:
        provider: "{{ device }}"
        cmd: "request high-availability state functional"
      when: is_initial_active

    - name: Re-enable config sync
      paloaltonetworks.panos.panos_ha:
        provider: "{{ device }}"
        state: present
        ha_config_sync: true

    - name: Force running-config sync from initial active back to peer
      paloaltonetworks.panos.panos_op:
        provider: "{{ device }}"
        cmd: "request high-availability sync-to-remote running-config"
      when: inventory_hostname == hostvars['localhost'].ha_active_host

    - name: Wait for original active role to return
      paloaltonetworks.panos.panos_active_in_ha:
        provider: "{{ device }}"
      register: final_role_check
      until: final_role_check.response.active | default(false)
      retries: 40
      delay: 30
      when: is_initial_active

    - name: Wait for original passive role to return
      paloaltonetworks.panos.panos_facts:
        provider: "{{ device }}"
        gather_subset: ["ha"]
      register: final_passive_state
      until: (final_passive_state.ansible_facts.ansible_net_ha_localstate | lower) == 'passive'
      retries: 40
      delay: 30
      when: is_initial_passive

    - name: Report HA upgrade result
      run_once: true
      ansible.builtin.debug:
        msg: |
          HA upgrade complete. Original active host ({{ hostvars['localhost'].ha_active_host }}) is active again and
          original passive host ({{ hostvars['localhost'].ha_passive_host }}) returned to passive. Backups saved under {{ backup_directory }}.
