---
- name: Audit Palo Alto security rules – missing meta + any-any insecure
  hosts: "{{ hosts | default('PRODUCTIONFIREWALL') }}"
  connection: local
  gather_facts: no

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Gather all security rules
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        state: gathered
        gathered_filter: "*"            # Fetch all rules
      register: sec_rules

    - name: Filter any-any insecure rules (source=any, dest=any, service=any)
      ansible.builtin.set_fact:
        any_any_insecure_rules: >-
          {{
            (sec_rules.gathered | default([]))
            | selectattr('source_ip', 'equalto', ['any'])
            | selectattr('destination_ip', 'equalto', ['any'])
            | selectattr('service', 'equalto', ['any'])
            | list
          }}

    - name: Filter rules missing description or audit_comment
      ansible.builtin.set_fact:
        rules_missing_meta: >-
          {{
            (sec_rules.gathered | default([]))
            | selectattr('description', 'equalto', None)
            | union(
                (sec_rules.gathered | default([]))
                | selectattr('audit_comment', 'equalto', None)
              )
            | list
          }}

    - name: Report insecure any-any rules
      ansible.builtin.debug:
        msg: |
          Insecure any-any rules (source=any, dest=any, service=any):
          {% for rule in any_any_insecure_rules %}
            - {{ rule.rule_name | default(rule.name) }}
          {% else %}
            (None found)
          {% endfor %}

    - name: Report rules missing description or comment
      ansible.builtin.debug:
        msg: |
          Rules missing description or audit_comment:
          {% for rule in rules_missing_meta %}
            - {{ rule.rule_name | default(rule.name) }}
          {% else %}
            (None found)
          {% endfor %}
