---
- name: Fetch configured DNS servers – PAN-OS
  hosts: "PRODUCTIONFIREWALL"
  connection: local
  gather_facts: no

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Gather full configuration of the firewall
      paloaltonetworks.panos.panos_facts:
        provider: "{{ device }}"
        gather_subset: ["config"]
      register: pan_config

    - name: Output raw configuration snippet for review
      ansible.builtin.debug:
        msg: "{{ pan_config.ansible_facts.ansible_net_config }}"

    - name: Extract configured DNS servers (placeholder logic)
      set_fact:
        dns_servers: >-
          {{
            pan_config.ansible_facts.ansible_net_config
            | regex_findall("(?<=<primary>)[0-9\\.]+(?=</primary>)")
          }}

    - name: Show configured DNS servers
      ansible.builtin.debug:
        msg: "Configured DNS servers are: {{ dns_servers }}"
