---
- name: Combined compliance checks – PAN-OS
  hosts: "{{ hosts | default('PRODUCTIONFIREWALL') }}"
  connection: local
  gather_facts: no

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"
    expected_dns_primary: "{{ dns_primary | default('8.8.8.8') }}"
    expected_dns_secondary: "{{ dns_secondary | default('192.168.29.3') }}"
    expected_ntp_primary: "{{ ntp_primary | default('10.1.1.10') }}"
    expected_ntp_secondary: "{{ ntp_secondary | default('10.1.1.11') }}"
    expected_syslog_ip: "{{ syslog_ip | default('192.168.29.3') }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Gather all security rules
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ device }}"
        gathered_filter: "*"
        state: gathered
      register: sec_rules

    - name: Compute any-any insecure rules
      ansible.builtin.set_fact:
        any_any_insecure_rules: >-
          {{
            (sec_rules.gathered | default([]))
            | selectattr('source_ip','equalto',['any'])
            | selectattr('destination_ip','equalto',['any'])
            | selectattr('service','equalto',['any'])
            | list
          }}

    - name: Compute SSL rules using non-standard ports
      ansible.builtin.set_fact:
        ssl_nonstandard_port_rules: >-
          {{
            (sec_rules.gathered | default([]))
            | selectattr('application','equalto',['ssl'])
            | rejectattr('service','equalto',['application-default'])
            | list
          }}

    - name: Gather running configuration
      paloaltonetworks.panos.panos_facts:
        provider: "{{ device }}"
        gather_subset: ["config"]
      register: pan_config

    - name: Ensure configuration XML retrieved
      ansible.built
