---
- name: Debug extraction – PAN-OS raw config
  hosts: "{{ hosts | default('PRODUCTIONFIREWALL') }}"
  connection: local
  gather_facts: no

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Gather full configuration
      paloaltonetworks.panos.panos_facts:
        provider: "{{ device }}"
        gather_subset: ["config"]
      register: pan_config

    - name: Ensure the config XML key exists
      ansible.builtin.assert:
        that:
          - pan_config.ansible_facts.ansible_net_config is defined
          - pan_config.ansible_facts.ansible_net_config | length > 0
        fail_msg: "No XML retrieved — check connectivity/credentials."

    - name: Output snippet around DNS/NTP/Syslog
      ansible.builtin.debug:
        msg: |
          {{ pan_config.ansible_facts.ansible_net_config
             | regex_search('(?s)<system>.*?</system>', '\\0') }}
