---
- name: Fetch configured NTP servers – PAN-OS
  hosts: "PRODUCTIONFIREWALL"
  connection: local
  gather_facts: no

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Gather configuration of the firewall
      paloaltonetworks.panos.panos_facts:
        provider: "{{ device }}"
        gather_subset: ["config"]
      register: pan_config

    - name: Output raw configuration snippet for review
      ansible.builtin.debug:
        msg: "{{ pan_config.ansible_facts.ansible_net_config }}"

    - name: Extract configured NTP servers (simple regex extraction)
      set_fact:
        ntp_servers: >-
          {{
            pan_config.ansible_facts.ansible_net_config
            | regex_findall("(?<=<ntp>).*?<primary>([0-9\\.]+)</primary>.*?<secondary>([0-9\\.]+)</secondary>", multiline=True)
          }}

    - name: Show configured NTP servers
      ansible.builtin.debug:
        msg: "Configured NTP servers (primary, secondary) = {{ ntp_servers }}"
