---
- name: Cisco 9300 Compliance Check
  hosts: cisco_switches
  gather_facts: no
  connection: network_cli

  vars:
    expected_syslog_ip: "192.168.29.3"
    expected_dns_primary: "192.168.29.3"
    expected_ntp_primary: "192.168.29.3"

  collections:
    - cisco.ios

  tasks:
    - name: Gather running configuration
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: running_config

    - name: Extract syslog servers
      set_fact:
        syslog_hosts: "{{ running_config.stdout[0].split('\n') | select('match', '^logging host ') | map('regex_replace', '^logging host ', '') | list }}"

    - name: Extract DNS servers
      set_fact:
        dns_servers: "{{ running_config.stdout[0].split('\n') | select('match', '^ip name-server ') | map('regex_replace', '^ip name-server ', '') | list }}"

    - name: Extract NTP servers
      set_fact:
        ntp_servers: "{{ running_config.stdout[0].split('\n') | select('match', '^ntp server ') | map('regex_replace', '^ntp server ', '') | list }}"

    - name: Check Syslog compliance
      assert:
        that:
          - expected_syslog_ip in syslog_hosts
        fail_msg: "Syslog NON-COMPLIANT: found {{ syslog_ho
