---
- name: Cisco 9300 Compliance Check
  hosts: cisco_switches
  gather_facts: no
  connection: network_cli

  vars:
    expected_syslog_ip: "192.168.29.3"
    expected_dns_primary: "192.168.29.3"
    expected_ntp_primary: "192.168.29.3"

  collections:
    - cisco.ios

  tasks:
    - name: Gather running configuration
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: running_config

    - name: Extract syslog servers
      set_fact:
        syslog_hosts: "{{ running_config.stdout[0].split('\n') | select('match', '^logging host ') | map('regex_replace', '^logging host ', '') | list }}"

    - name: Extract DNS servers
      set_fact:
        dns_servers: "{{ running_config.stdout[0].split('\n') | select('match', '^ip name-server ') | map('regex_replace', '^ip name-server ', '') | list }}"

    - name: Extract NTP servers
      set_fact:
        ntp_servers: "{{ running_config.stdout[0].split('\n') | select('match', '^ntp server ') | map('regex_replace', '^ntp server ', '') | list }}"

    - name: Check Syslog compliance
      assert:
        that:
          - expected_syslog_ip in syslog_hosts
        fail_msg: "Syslog NON-COMPLIANT: found {{ syslog_hosts }}"
        success_msg: "Syslog COMPLIANT"

    - name: Check DNS compliance
      assert:
        that:
          - expected_dns_primary in dns_servers
        fail_msg: "DNS NON-COMPLIANT: found {{ dns_servers }}"
        success_msg: "DNS COMPLIANT"

    - name: Check NTP compliance
      assert:
        that:
          - expected_ntp_primary in ntp_servers
        fail_msg: "NTP NON-COMPLIANT: found {{ ntp_servers }}"
        success_msg: "NTP COMPLIANT"

    - name: Gather interface configuration
      cisco.ios.ios_command:
        commands:
          - show running-config | section interface
      register: intf_config

    - name: Check PortFast, Port Security, and Storm Control compliance
      vars:
        interfaces: "{{ intf_config.stdout[0].split('interface ') | select('search', '^GigabitEthernet') | list }}"
      block:
        - name: Evaluate compliance for each interface
          loop: "{{ interfaces }}"
          loop_control:
            label: "{{ item.split('\n')[0] }}"
          vars:
            config: "{{ item }}"
          block:
            - name: Check PortFast
              assert:
                that:
                  - "'spanning-tree portfast' in config"
                fail_msg: "PortFast NON-COMPLIANT on {{ item.split('\n')[0] }}"
                success_msg: "PortFast COMPLIANT on {{ item.split('\n')[0] }}"

            - name: Check Port Security
              assert:
                that:
                  - "'switchport port-security' in config"
                fail_msg: "Port Security NON-COMPLIANT on {{ item.split('\n')[0] }}"
                success_msg: "Port Security COMPLIANT on {{ item.split('\n')[0] }}"

            - name: Check Storm Control
              assert:
                that:
                  - "'storm-control' in config"
                fail_msg: "Storm Control NON-COMPLIANT on {{ item.split('\n')[0] }}"
                success_msg: "Storm Control COMPLIANT on {{ item.split('\n')[0] }}"
