---
- name: Configure VLANs and SSH on Cisco Catalyst 9300
  hosts: 192.168.29.164
  gather_facts: no
  connection: network_cli
  collections:
    - cisco.ios

  vars:
    vlan10_interfaces:
      - GigabitEthernet2/0/10
      - GigabitEthernet2/0/11
      - GigabitEthernet2/0/12
      - GigabitEthernet2/0/13
      - GigabitEthernet2/0/14
    vlan20_interfaces:
      - GigabitEthernet2/0/15
      - GigabitEthernet2/0/16
      - GigabitEthernet2/0/17
      - GigabitEthernet2/0/18
      - GigabitEthernet2/0/19
      - GigabitEthernet2/0/20

  tasks:
    - name: Create VLANs 10 and 20
      cisco.ios.ios_vlans:
        config:
          - name: USERS
            vlan_id: 30
          - name: SERVERS
            vlan_id: 40

    - name: Assign VLAN 30 to interfaces GigabitEthernet2/0/10-14
      cisco.ios.ios_config:
        lines:
          - "interface {{ item }}"
          - "switchport mode access"
          - "switchport access vlan 30"
        parents: "interface range {{ item }}"
      loop: "{{ vlan30_interfaces }}"
      when: vlan30_interfaces is defined

    - name: Assign VLAN 40 to interfaces GigabitEthernet2/0/15-20
      cisco.ios.ios_config:
        lines:
          - "interface {{ item }}"
          - "switchport mode access"
          - "switchport access vlan 40"
        parents: "interface range {{ item }}"
      loop: "{{ vlan40_interfaces }}"
      when: vlan40_interfaces is defined

    
