---
- name: Check Port-Security on interface {{ iface_name }}
  ansible.builtin.debug:
    msg: "Port-Security on {{ iface_name }} : {{ 'COMPLIANT' if ('switchport port-security' in iface_block) else 'NON-COMPLIANT' }}"

- name: Check PortFast on interface {{ iface_name }}
  ansible.builtin.debug:
    msg: "PortFast on {{ iface_name }} : {{ 'COMPLIANT' if ('spanning-tree portfast' in iface_block) else 'NON-COMPLIANT' }}"

- name: Check Storm-Control on interface {{ iface_name }}
  ansible.builtin.debug:
    msg: "Storm-Control on {{ iface_name }} : {{ 'COMPLIANT' if ('storm-control' in iface_block) else 'NON-COMPLIANT' }}"
