---
# Sample Event-Driven Ansible Rulebook for AAP 2.6
# This rulebook demonstrates various event sources and automation responses

- name: Network Device Alert Response
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Handle High CPU Alert
      condition: event.payload.alert_type == "high_cpu" and event.payload.threshold > 80
      action:
        run_job_template:
          name: "Network Device Diagnostics"
          organization: "Default"
          job_args:
            extra_vars:
              device_name: "{{ event.payload.device_name }}"
              cpu_usage: "{{ event.payload.threshold }}"

    - name: Handle Interface Down Event
      condition: event.payload.alert_type == "interface_down"
      action:
        run_job_template:
          name: "Interface Troubleshooting"
          organization: "Default"
          job_args:
            extra_vars:
              device_name: "{{ event.payload.device_name }}"
              interface: "{{ event.payload.interface }}"

- name: Firewall Policy Compliance Monitor
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: Detect Any-Any Policy Violation
      condition: event.payload.policy_type == "any-any" and event.payload.action == "created"
      action:
        run_job_template:
          name: "Security policy with any-any"
          organization: "Default"
          job_args:
            extra_vars:
              firewall_name: "{{ event.payload.firewall_name }}"
              policy_id: "{{ event.payload.policy_id }}"

    - name: Non-Standard Port Policy Alert
      condition: event.payload.port not in [80, 443, 22, 21, 25] and event.payload.policy_type == "service"
      action:
        run_job_template:
          name: "Policies on non-standard-ports-2"
          organization: "Default"
          job_args:
            extra_vars:
              firewall_name: "{{ event.payload.firewall_name }}"
              port: "{{ event.payload.port }}"

- name: Device Configuration Drift Detection
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5002
  rules:
    - name: Cisco Switch Configuration Drift
      condition: event.payload.device_type == "cisco_switch" and event.payload.drift_detected == true
      action:
        run_job_template:
          name: "Switch_Compliance checks"
          organization: "Default"
          job_args:
            extra_vars:
              device_name: "{{ event.payload.device_name }}"
              config_version: "{{ event.payload.config_version }}"

    - name: Palo Alto Firewall Drift
      condition: event.payload.device_type == "palo_alto" and event.payload.drift_detected == true
      action:
        run_job_template:
          name: "PA_FW_Compliance_FinalV"
          organization: "Default"
          job_args:
            extra_vars:
              firewall_name: "{{ event.payload.device_name }}"

- name: Scheduled Maintenance Events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5003
  rules:
    - name: Trigger Software Upgrade
      condition: event.payload.maintenance_type == "software_upgrade" and event.payload.approved == true
      action:
        run_job_template:
          name: "pan_os_upgrade"
          organization: "Default"
          job_args:
            extra_vars:
              target_device: "{{ event.payload.device_name }}"
              target_version: "{{ event.payload.target_version }}"

    - name: ZTP Provisioning Request
      condition: event.payload.event_type == "new_device" and event.payload.provisioning_required == true
      action:
        run_job_template:
          name: "{{ 'PaloAlto440_ztp' if event.payload.device_model == 'PA-440' else 'Cisco9300_ztp' }}"
          organization: "Default"
          job_args:
            extra_vars:
              device_ip: "{{ event.payload.device_ip }}"
              device_serial: "{{ event.payload.serial_number }}"

- name: Multi-Action Rule Example
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5004
  rules:
    - name: Critical Security Event
      condition: event.payload.severity == "critical" and event.payload.category == "security"
      actions:
        - run_job_template:
            name: "get-system-info"
            organization: "Default"
        - debug:
            msg: "Critical security event detected on {{ event.payload.device_name }}"
        - print_event:
            pretty: true
