- name: Switch Interface Down Remediation Rulebook
  hosts: 192.168.29.164
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: interface_down_rule
      condition:
        event.payload.message is search("changed state to administratively down", ignorecase=true)
      action:
        run_job_template:
          name: "Remediate_Switch_Port_Down"
          extra_vars:
            interface_name: "{{ event.payload.interface_name }}"
            target_switch: "{{ event.payload.switch_name }}"

