---
- name: ISP Link Failover Rulebook
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001
  rules:
    - name: Primary ISP Interface Down
      condition:
        all:
          - event.payload.host == "192.168.29.164"         # adjust if your hostname differs
          - event.payload.interface == "GigabitEthernet2/0/2"
          - event.payload.status == "down"
      action:
        run_job_template:
          name: ISP_Failover_Job
          extra_vars:
            router: "{{ event.payload.host }}"
            primary_iface: "GigabitEthernet2/0/2"
            backup_iface:  "GigabitEthernet2/0/3"
            primary_next_hop: "106.51.64.1"             # adjust to your actual next-hop if different
            backup_next_hop:  "125.99.242.1"             # adjust to your actual backup next-hop

