---
- name: Standalone PAN-OS Upgrade with Config Backup
  hosts: "{{ hosts | default('UPGRADEFW') }}"
  connection: local

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"

    backup_filename: "{{ backup_filename | default('panos-config-backup.xml') }}"
    backup_retrieve_dir: "{{ backup_retrieve_dir | default(playbook_dir) }}"
    backup_local_path: "{{ backup_retrieve_dir | default(playbook_dir) }}/{{ backup_filename }}"
    commit_restored_config: "{{ commit_restored_config | default(true) }}"

    reboot_between_steps: true
    quiet_polling: true

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Validate upgrade_path is provided
      assert:
        that:
          - upgrade_path is defined
          - upgrade_path | length > 0
        fail_msg: 'You must provide -e upgrade_path=''["10.1.14","11.0.0","11.1.5"]'''

    - name: Check device readiness before configuration backup
      paloaltonetworks.panos.panos_check:
        provider: "{{ device }}"
      register: pre_backup_ready
      until: pre_backup_ready is not failed and pre_backup_ready.msg == 'Device is ready.'
      retries: 10
      delay: 10

    - name: Export running configuration backup
      paloaltonetworks.panos.panos_export:
        provider: "{{ device }}"
        category: "configuration"
        filename: "{{ backup_local_path }}"
        create_directory: true
      register: backup_export

    - name: Check if device is ready before content upgrade
      paloaltonetworks.panos.panos_check:
        provider: "{{ device }}"
      register: ready_check
      until: ready_check is not failed and ready_check.msg == 'Device is ready.'
      retries: 10
      delay: 10

    - name: Refresh content update index
      paloaltonetworks.panos.panos_op:
        provider: "{{ device }}"
        cmd: "request content upgrade check"
      register: content_check

    - name: Download latest content update
      paloaltonetworks.panos.panos_op:
        provider: "{{ device }}"
        cmd: "request content upgrade download latest"
      register: content_download

    - name: Extract job ID for content download
      set_fact:
        content_download_jobid: "{{ content_download.stdout_xml | regex_search('<job>(\\d+)</job>', '\\1') | first | default('') }}"

    - name: Wait for content download job to complete
      paloaltonetworks.panos.panos_op:
        provider: "{{ device }}"
        cmd: "<show><jobs><id>{{ content_download_jobid }}</id></jobs></show>"
        cmd_is_xml: true
      register: content_download_result
      until: content_download_result.stdout_xml is search('<status>FIN</status>')
      retries: 300
      delay: 10
      failed_when: content_download_result.stdout_xml is search('<result>FAIL</result>')
      when: content_download_jobid | length > 0
      no_log: true

    - name: Install latest content update
      paloaltonetworks.panos.panos_op:
        provider: "{{ device }}"
        cmd: "request content upgrade install version latest"
      register: content_install

    - name: Extract job ID for content install
      set_fact:
        content_install_jobid: "{{ content_install.stdout_xml | regex_search('<job>(\\d+)</job>', '\\1') | first | default('') }}"

    - name: Wait for content install job to complete
      paloaltonetworks.panos.panos_op:
        provider: "{{ device }}"
        cmd: "<show><jobs><id>{{ content_install_jobid }}</id></jobs></show>"
        cmd_is_xml: true
      register: content_install_result
      until: >
        content_install_result.stdout_xml is search('<status>FIN</status>') or
        content_install_result.stdout_xml is search('<status>FAIL</status>')
      retries: 300
      delay: 10
      failed_when: >
        (content_install_result.stdout_xml is search('<status>FIN</status>') and
         content_install_result.stdout_xml is search('<result>FAIL</result>')) or
        content_install_result.stdout_xml is search('<status>FAIL</status>')
      when: content_install_jobid | length > 0
      no_log: true

    - name: Wait for device readiness after content install
      paloaltonetworks.panos.panos_check:
        provider: "{{ device }}"
      register: ready_after_content
      until: ready_after_content is not failed and ready_after_content.msg == 'Device is ready.'
      retries: 60
      delay: 15
      no_log: true

    - name: Execute staged OS upgrade for {{ item }}
      include_tasks: tasks/upgrade_step_v2.yml
      loop: "{{ upgrade_path }}"
      loop_control:
        label: "{{ item }}"
      vars:
        version_item: "{{ item }}"

    - name: Wait for device readiness after final upgrade
      paloaltonetworks.panos.panos_check:
        provider: "{{ device }}"
      register: ready_post_upgrade
      until: ready_post_upgrade is not failed and ready_post_upgrade.msg == 'Device is ready.'
      retries: 60
      delay: 15
      no_log: true

    - name: Import saved configuration to device
      paloaltonetworks.panos.panos_import:
        provider: "{{ device }}"
        category: "configuration"
        file: "{{ backup_local_path }}"
      register: config_import

    - name: Load saved configuration
      paloaltonetworks.panos.panos_loadcfg:
        ip_address: "{{ device.ip_address }}"
        username: "{{ device.username }}"
        password: "{{ device.password }}"
        file: "{{ config_import.filename | default(backup_export.filename | default(backup_filename)) }}"
        commit: false

    - name: Commit restored configuration
      paloaltonetworks.panos.panos_commit_firewall:
        provider: "{{ device }}"
      when: commit_restored_config | bool
      register: commit_restore

    - name: Wait for device readiness after restoring configuration
      paloaltonetworks.panos.panos_check:
        provider: "{{ device }}"
      register: ready_after_restore
      until: ready_after_restore is not failed and ready_after_restore.msg == 'Device is ready.'
      retries: 60
      delay: 15
      no_log: true

    - name: Gather final system facts
      paloaltonetworks.panos.panos_facts:
        provider: "{{ device }}"
        gather_subset: ["system"]
      register: final_facts

    - name: Display final version
      debug:
        msg: "Upgrade complete. Final PAN-OS version: {{ final_facts.ansible_facts.ansible_net_version }}"
